Solving the following compile time error
error: moving ‘a’ of type ‘arduino::String’ to itself [-Werror=self-move]
Which may happen if if GCC_VERSION is not defined, and instead __GNUC__
is defined